// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzgxgndW0ym7exVsJAz8xB0-g0wW8EQZg',
    appId: '1:974199527585:web:9776e65ae8dd84531df8e0',
    messagingSenderId: '974199527585',
    projectId: 'formative2-8d15c',
    authDomain: 'formative2-8d15c.firebaseapp.com',
    storageBucket: 'formative2-8d15c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQb8nzMBQd8l7-BOL47KtgED9Zadly788',
    appId: '1:974199527585:android:4b0058718e17de981df8e0',
    messagingSenderId: '974199527585',
    projectId: 'formative2-8d15c',
    storageBucket: 'formative2-8d15c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0OoU5TpZlpK8hRUI26Yf2Ncu0p4GhFGU',
    appId: '1:974199527585:ios:a77e6957d1f846641df8e0',
    messagingSenderId: '974199527585',
    projectId: 'formative2-8d15c',
    storageBucket: 'formative2-8d15c.firebasestorage.app',
    iosBundleId: 'com.example.gakwayaformativeassignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0OoU5TpZlpK8hRUI26Yf2Ncu0p4GhFGU',
    appId: '1:974199527585:ios:a77e6957d1f846641df8e0',
    messagingSenderId: '974199527585',
    projectId: 'formative2-8d15c',
    storageBucket: 'formative2-8d15c.firebasestorage.app',
    iosBundleId: 'com.example.gakwayaformativeassignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzgxgndW0ym7exVsJAz8xB0-g0wW8EQZg',
    appId: '1:974199527585:web:18c5b423a96554271df8e0',
    messagingSenderId: '974199527585',
    projectId: 'formative2-8d15c',
    authDomain: 'formative2-8d15c.firebaseapp.com',
    storageBucket: 'formative2-8d15c.firebasestorage.app',
  );
}
